### ISSUE TITLE
Add HTTPS connection option

### ISSUE THREAD

**Issue by taneltm** [veelenga/jira_report#7]
HTTP may not be allowed.

**Comment by veelenga** [comment]
@taneltm It was planned for next release. Coming soon.
Thanks for reporting issue.

**Comment by veelenga** [comment]
Fixed in 0.1.4. Now you can pass `http` or  `https` urls.

Do not forget to update your gem.

**Comment by taneltm** [comment]
Awesome, I'll give it a try very soon!
