### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by yakov-setplex** [veelenga/jira_report#9]
........
Done installing documentation for domain_name, http-cookie, jira_report, mime-types, netrc, rest-client, unf after 9 seconds
7 gems installed

 $ jira-report 
Jira site address: jira.setplex.net:8080
Username for 'jira.setplex.net:8080': yakov
Password for 'jira.setplex.net:8080': 
Connecting to 'jira.setplex.net:8080'. Pls wait...
error: '400 Bad Request'

**Comment by veelenga** [comment]
Thanks for reporting this. Could you please try setting your url starting with http or https? Just like in sample in readme

**Comment by veelenga** [comment]
Seems like not really relevant. Will close this for now. Be free to reopen once your problem not solved.
